//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDelServicio.Contable_srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asiento", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class Asiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BatchNumbEncabezadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfitCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProyectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClienteDelServicio.Contable_srv.AsientoDetalle> lineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int transIDEncabezadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BatchNumbEncabezado {
            get {
                return this.BatchNumbEncabezadoField;
            }
            set {
                if ((this.BatchNumbEncabezadoField.Equals(value) != true)) {
                    this.BatchNumbEncabezadoField = value;
                    this.RaisePropertyChanged("BatchNumbEncabezado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfitCode {
            get {
                return this.ProfitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfitCodeField, value) != true)) {
                    this.ProfitCodeField = value;
                    this.RaisePropertyChanged("ProfitCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proyect {
            get {
                return this.ProyectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProyectField, value) != true)) {
                    this.ProyectField = value;
                    this.RaisePropertyChanged("Proyect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoTransaccion {
            get {
                return this.codigoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoTransaccionField, value) != true)) {
                    this.codigoTransaccionField = value;
                    this.RaisePropertyChanged("codigoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClienteDelServicio.Contable_srv.AsientoDetalle> lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int transIDEncabezado {
            get {
                return this.transIDEncabezadoField;
            }
            set {
                if ((this.transIDEncabezadoField.Equals(value) != true)) {
                    this.transIDEncabezadoField = value;
                    this.RaisePropertyChanged("transIDEncabezado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsientoDetalle", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class AsientoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BaseRetencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRetencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Line_IDDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PorcentaRetencionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reference1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reference2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reference3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteDelServicio.Contable_srv.SocioNegocio socioNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int transIDDetalleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountCode {
            get {
                return this.AccountCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCodeField, value) != true)) {
                    this.AccountCodeField = value;
                    this.RaisePropertyChanged("AccountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BaseRetencion {
            get {
                return this.BaseRetencionField;
            }
            set {
                if ((this.BaseRetencionField.Equals(value) != true)) {
                    this.BaseRetencionField = value;
                    this.RaisePropertyChanged("BaseRetencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRetencion {
            get {
                return this.CodigoRetencionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRetencionField, value) != true)) {
                    this.CodigoRetencionField = value;
                    this.RaisePropertyChanged("CodigoRetencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Debit {
            get {
                return this.DebitField;
            }
            set {
                if ((this.DebitField.Equals(value) != true)) {
                    this.DebitField = value;
                    this.RaisePropertyChanged("Debit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Line_IDDetalle {
            get {
                return this.Line_IDDetalleField;
            }
            set {
                if ((this.Line_IDDetalleField.Equals(value) != true)) {
                    this.Line_IDDetalleField = value;
                    this.RaisePropertyChanged("Line_IDDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PorcentaRetenciones {
            get {
                return this.PorcentaRetencionesField;
            }
            set {
                if ((this.PorcentaRetencionesField.Equals(value) != true)) {
                    this.PorcentaRetencionesField = value;
                    this.RaisePropertyChanged("PorcentaRetenciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectCode {
            get {
                return this.ProjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectCodeField, value) != true)) {
                    this.ProjectCodeField = value;
                    this.RaisePropertyChanged("ProjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference1 {
            get {
                return this.Reference1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference1Field, value) != true)) {
                    this.Reference1Field = value;
                    this.RaisePropertyChanged("Reference1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference2 {
            get {
                return this.Reference2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference2Field, value) != true)) {
                    this.Reference2Field = value;
                    this.RaisePropertyChanged("Reference2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference3 {
            get {
                return this.Reference3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference3Field, value) != true)) {
                    this.Reference3Field = value;
                    this.RaisePropertyChanged("Reference3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteDelServicio.Contable_srv.SocioNegocio socioNegocio {
            get {
                return this.socioNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.socioNegocioField, value) != true)) {
                    this.socioNegocioField = value;
                    this.RaisePropertyChanged("socioNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int transIDDetalle {
            get {
                return this.transIDDetalleField;
            }
            set {
                if ((this.transIDDetalleField.Equals(value) != true)) {
                    this.transIDDetalleField = value;
                    this.RaisePropertyChanged("transIDDetalle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocioNegocio", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class SocioNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicTradNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular {
            get {
                return this.CellularField;
            }
            set {
                if ((object.ReferenceEquals(this.CellularField, value) != true)) {
                    this.CellularField = value;
                    this.RaisePropertyChanged("Cellular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicTradNum {
            get {
                return this.LicTradNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LicTradNumField, value) != true)) {
                    this.LicTradNumField = value;
                    this.RaisePropertyChanged("LicTradNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConexionWS", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class ConexionWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContrasenaField;
        
        private string UsuarioField;
        
        private string UsuarioWsNsftContabilidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UsuarioWsNsftContabilidad {
            get {
                return this.UsuarioWsNsftContabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioWsNsftContabilidadField, value) != true)) {
                    this.UsuarioWsNsftContabilidadField = value;
                    this.RaisePropertyChanged("UsuarioWsNsftContabilidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataAccessFault", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class DataAccessFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorSAPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorIDField, value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorSAP {
            get {
                return this.ErrorSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSAPField, value) != true)) {
                    this.ErrorSAPField = value;
                    this.RaisePropertyChanged("ErrorSAP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WsNsftContabilidad", ConfigurationName="Contable_srv.WsNsftContabilidad")]
    public interface WsNsftContabilidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContable", ReplyAction="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteDelServicio.Contable_srv.DataAccessFault), Action="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContableDataAccessFaultF" +
            "ault", Name="DataAccessFault")]
        int CrearAsientoContable(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContable", ReplyAction="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContableResponse")]
        System.Threading.Tasks.Task<int> CrearAsientoContableAsync(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsNsftContabilidadChannel : ClienteDelServicio.Contable_srv.WsNsftContabilidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsNsftContabilidadClient : System.ServiceModel.ClientBase<ClienteDelServicio.Contable_srv.WsNsftContabilidad>, ClienteDelServicio.Contable_srv.WsNsftContabilidad {
        
        public WsNsftContabilidadClient() {
        }
        
        public WsNsftContabilidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsNsftContabilidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNsftContabilidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNsftContabilidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearAsientoContable(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion) {
            return base.Channel.CrearAsientoContable(asiento, conexion);
        }
        
        public System.Threading.Tasks.Task<int> CrearAsientoContableAsync(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion) {
            return base.Channel.CrearAsientoContableAsync(asiento, conexion);
        }
    }
}
