//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDelServicio.Contable_srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asiento", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class Asiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutoVatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RefDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StampTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TaxDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VatDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClienteDelServicio.Contable_srv.AsientoDetalle> lineasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoVat {
            get {
                return this.AutoVatField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoVatField, value) != true)) {
                    this.AutoVatField = value;
                    this.RaisePropertyChanged("AutoVat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ref1 {
            get {
                return this.Ref1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref1Field, value) != true)) {
                    this.Ref1Field = value;
                    this.RaisePropertyChanged("Ref1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ref2 {
            get {
                return this.Ref2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref2Field, value) != true)) {
                    this.Ref2Field = value;
                    this.RaisePropertyChanged("Ref2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RefDate {
            get {
                return this.RefDateField;
            }
            set {
                if ((this.RefDateField.Equals(value) != true)) {
                    this.RefDateField = value;
                    this.RaisePropertyChanged("RefDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StampTax {
            get {
                return this.StampTaxField;
            }
            set {
                if ((object.ReferenceEquals(this.StampTaxField, value) != true)) {
                    this.StampTaxField = value;
                    this.RaisePropertyChanged("StampTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TaxDate {
            get {
                return this.TaxDateField;
            }
            set {
                if ((this.TaxDateField.Equals(value) != true)) {
                    this.TaxDateField = value;
                    this.RaisePropertyChanged("TaxDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransCode {
            get {
                return this.TransCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransCodeField, value) != true)) {
                    this.TransCodeField = value;
                    this.RaisePropertyChanged("TransCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VatDate {
            get {
                return this.VatDateField;
            }
            set {
                if ((this.VatDateField.Equals(value) != true)) {
                    this.VatDateField = value;
                    this.RaisePropertyChanged("VatDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClienteDelServicio.Contable_srv.AsientoDetalle> lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsientoDetalle", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class AsientoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DuoDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcrCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcrCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfitCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref3LineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RefDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TaxDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string U_InfoCo01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteDelServicio.Contable_srv.SocioNegocio socioNegocioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Debit {
            get {
                return this.DebitField;
            }
            set {
                if ((this.DebitField.Equals(value) != true)) {
                    this.DebitField = value;
                    this.RaisePropertyChanged("Debit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DuoDate {
            get {
                return this.DuoDateField;
            }
            set {
                if ((this.DuoDateField.Equals(value) != true)) {
                    this.DuoDateField = value;
                    this.RaisePropertyChanged("DuoDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineMemo {
            get {
                return this.LineMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.LineMemoField, value) != true)) {
                    this.LineMemoField = value;
                    this.RaisePropertyChanged("LineMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OcrCode2 {
            get {
                return this.OcrCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.OcrCode2Field, value) != true)) {
                    this.OcrCode2Field = value;
                    this.RaisePropertyChanged("OcrCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OcrCode3 {
            get {
                return this.OcrCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.OcrCode3Field, value) != true)) {
                    this.OcrCode3Field = value;
                    this.RaisePropertyChanged("OcrCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfitCode {
            get {
                return this.ProfitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfitCodeField, value) != true)) {
                    this.ProfitCodeField = value;
                    this.RaisePropertyChanged("ProfitCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ref1 {
            get {
                return this.Ref1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref1Field, value) != true)) {
                    this.Ref1Field = value;
                    this.RaisePropertyChanged("Ref1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ref2 {
            get {
                return this.Ref2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref2Field, value) != true)) {
                    this.Ref2Field = value;
                    this.RaisePropertyChanged("Ref2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ref3Line {
            get {
                return this.Ref3LineField;
            }
            set {
                if ((object.ReferenceEquals(this.Ref3LineField, value) != true)) {
                    this.Ref3LineField = value;
                    this.RaisePropertyChanged("Ref3Line");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RefDate {
            get {
                return this.RefDateField;
            }
            set {
                if ((this.RefDateField.Equals(value) != true)) {
                    this.RefDateField = value;
                    this.RaisePropertyChanged("RefDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TaxDate {
            get {
                return this.TaxDateField;
            }
            set {
                if ((this.TaxDateField.Equals(value) != true)) {
                    this.TaxDateField = value;
                    this.RaisePropertyChanged("TaxDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string U_InfoCo01 {
            get {
                return this.U_InfoCo01Field;
            }
            set {
                if ((object.ReferenceEquals(this.U_InfoCo01Field, value) != true)) {
                    this.U_InfoCo01Field = value;
                    this.RaisePropertyChanged("U_InfoCo01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteDelServicio.Contable_srv.SocioNegocio socioNegocio {
            get {
                return this.socioNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.socioNegocioField, value) != true)) {
                    this.socioNegocioField = value;
                    this.RaisePropertyChanged("socioNegocio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocioNegocio", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class SocioNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicTradNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular {
            get {
                return this.CellularField;
            }
            set {
                if ((object.ReferenceEquals(this.CellularField, value) != true)) {
                    this.CellularField = value;
                    this.RaisePropertyChanged("Cellular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicTradNum {
            get {
                return this.LicTradNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LicTradNumField, value) != true)) {
                    this.LicTradNumField = value;
                    this.RaisePropertyChanged("LicTradNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConexionWS", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class ConexionWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContrasenaField;
        
        private string UsuarioField;
        
        private string UsuarioWsNsftContabilidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UsuarioWsNsftContabilidad {
            get {
                return this.UsuarioWsNsftContabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioWsNsftContabilidadField, value) != true)) {
                    this.UsuarioWsNsftContabilidadField = value;
                    this.RaisePropertyChanged("UsuarioWsNsftContabilidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataAccessFault", Namespace="http://WsNsftContabilidad")]
    [System.SerializableAttribute()]
    public partial class DataAccessFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorSAPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorIDField, value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorSAP {
            get {
                return this.ErrorSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSAPField, value) != true)) {
                    this.ErrorSAPField = value;
                    this.RaisePropertyChanged("ErrorSAP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WsNsftContabilidad", ConfigurationName="Contable_srv.WsNsftContabilidad")]
    public interface WsNsftContabilidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContable", ReplyAction="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteDelServicio.Contable_srv.DataAccessFault), Action="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContableDataAccessFaultF" +
            "ault", Name="DataAccessFault")]
        int CrearAsientoContable(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContable", ReplyAction="http://WsNsftContabilidad/WsNsftContabilidad/CrearAsientoContableResponse")]
        System.Threading.Tasks.Task<int> CrearAsientoContableAsync(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsNsftContabilidadChannel : ClienteDelServicio.Contable_srv.WsNsftContabilidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsNsftContabilidadClient : System.ServiceModel.ClientBase<ClienteDelServicio.Contable_srv.WsNsftContabilidad>, ClienteDelServicio.Contable_srv.WsNsftContabilidad {
        
        public WsNsftContabilidadClient() {
        }
        
        public WsNsftContabilidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsNsftContabilidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNsftContabilidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNsftContabilidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearAsientoContable(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion) {
            return base.Channel.CrearAsientoContable(asiento, conexion);
        }
        
        public System.Threading.Tasks.Task<int> CrearAsientoContableAsync(ClienteDelServicio.Contable_srv.Asiento asiento, ClienteDelServicio.Contable_srv.ConexionWS conexion) {
            return base.Channel.CrearAsientoContableAsync(asiento, conexion);
        }
    }
}
